site_name: راهنمای Elm
theme:
  name: gitbook
nav:
  - Introduction: index.md
  - Core Language: core_language.md
  - The Elm Architecture:
    - architecture/index.md
    - architecture/buttons.md
    - architecture/text_fields.md
    - architecture/forms.md
  - Types:
    - types/index.md
    - types/reading_types.md
    - types/type_aliases.md
    - types/custom_types.md
    - types/pattern_matching.md
  - Error Handling:
    - error_handling/index.md
    - error_handling/maybe.md
    - error_handling/result.md
  - Commands and Subscriptions:
    - effects/index.md
    - effects/http.md
    - effects/json.md
    - effects/random.md
    - effects/time.md
  - Installation:
    - install/index.md
    - install/editor.md
    - install/elm.md
  - JavaScript Interop:
    - interop/index.md
    - interop/flags.md
    - interop/ports.md
    - interop/custom_elements.md
    - interop/limits.md
  - Web Apps:
    - web_apps/index.md
    - web_apps/navigation.md
    - web_apps/url_parsing.md
    - web_apps/modules.md
    - web_apps/structure.md
  - Optimization:
    - optimization/index.md
    - optimization/lazy.md
    - optimization/keyed.md
    - optimization/asset_size.md
  - Next Steps: next_steps.md
  - Appendix:
    - appendix/types_as_sets.md
    - appendix/types_as_bits.md
    - appendix/function_types.md