site_name: راهنمای Elm
site_url: https://guide.elm-lang.ir
site_description: راهنمای رسمی زبان برنامه‌نویسی Elm
site_author: Novid Emami
copyright: CC BY-NC 4.0

theme:
  name: material
  language: fa
  font:
    text: Noto Sans Arabic
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - navigation.footer
    - navigation.section
    - navigation.expand
    - navigation.indexes
    - search.share
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
  plugins:
    - offline
    - search

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/novid/guide.elm-lang.ir
      name: novid on GitHub

    - icon: fontawesome/brands/linkedin 
      link: https://linkedin.com/in/novid
      name: novid on LinkedIn

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - toc:
      permalink: true
      permalink_title: Permalink

nav:
  - مقدمه: index.md
  - مفاهیم پایه: core_language.md
  - معماری Elm:
    - architecture/index.md
    - architecture/buttons.md
    - architecture/text_fields.md
    - architecture/forms.md
  - نوع داده:
    - types/index.md
    - types/reading_types.md
    - types/type_aliases.md
    - types/custom_types.md
    - types/pattern_matching.md
  - مدیریت خطا:
    - error_handling/index.md
    - error_handling/maybe.md
    - error_handling/result.md
  - دستور و اشتراک:
    - effects/index.md
    - effects/http.md
    - effects/json.md
    - effects/random.md
    - effects/time.md
  - نصب:
    - install/index.md
    - install/editor.md
    - install/elm.md
  - تعامل با جاوااسکریپت:
    - interop/index.md
    - interop/flags.md
    - interop/ports.md
    - interop/custom_elements.md
    - interop/limits.md
  - وب اپلیکیشن:
    - web_apps/index.md
    - web_apps/navigation.md
    - web_apps/url_parsing.md
    - web_apps/modules.md
    - web_apps/structure.md
  - بهینه‌سازی:
    - optimization/index.md
    - optimization/lazy.md
    - optimization/keyed.md
    - optimization/asset_size.md
  - مراحل بعدی: next_steps.md
  - ضمیمه:
    - appendix/types_as_sets.md
    - appendix/types_as_bits.md
    - appendix/function_types.md